//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothersForHand.Date
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsChangeHistory
    {
        public int HistoryID { get; set; }
        public int MaterialID { get; set; }
        public string Operation { get; set; }
        public int CountInStock { get; set; }
        public System.DateTime Date { get; set; }
    }
}
