//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothersForHand.Date
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.PossibleSupliersMaterial = new HashSet<PossibleSupliersMaterial>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public int MaterialTypeID { get; set; }
        public byte[] Image { get; set; }
        public decimal Cost { get; set; }
        public int CountInStock { get; set; }
        public int MinCount { get; set; }
        public int CountInPackage { get; set; }
        public int UnitMeasureID { get; set; }
        public string Description { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual UnitMeasure UnitMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleSupliersMaterial> PossibleSupliersMaterial { get; set; }
    }
}
