//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothersForHand.Date
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossibleSupliersMaterial
    {
        public int PossibleSuplierID { get; set; }
        public int MaterialID { get; set; }
        public int SuplierID { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Suplier Suplier { get; set; }
    }
}
